Repository FGRed/brandis-web, pull requests merged in 2022-06, with the labels that each got.

#4 Bw 2 adding user entity
  src/main/java/com/brandis/brandisweb/model/BUser.java
  src/main/java/com/brandis/brandisweb/repository/BUserRepository.java
Labels: New functionality

#5 Added BGame repository and model.
  src/main/java/com/brandis/brandisweb/model/BGame.java
  src/main/java/com/brandis/brandisweb/repository/BGameRepository.java
Labels: New functionality

#16 #16 added functionality for BUser
  src/main/java/com/brandis/brandisweb/config/BeanConfig.java
  src/main/java/com/brandis/brandisweb/config/DatabaseInitzr.java
  src/main/java/com/brandis/brandisweb/config/SecurityConfig.java
  src/main/java/com/brandis/brandisweb/exception/UserException.java
  src/main/java/com/brandis/brandisweb/model/BUser.java
  src/main/java/com/brandis/brandisweb/repository/BUserRepository.java
  src/main/java/com/brandis/brandisweb/service/BUserService.java
  src/main/java/com/brandis/brandisweb/service/BaseService.java
Labels: New functionality

#21 Created BSavedGame, BSavedRepository, BGameService, BSavedGameService…
  src/main/java/com/brandis/brandisweb/config/DatabaseInitzr.java
  src/main/java/com/brandis/brandisweb/exception/GameException.java
  src/main/java/com/brandis/brandisweb/model/bgame/AbstractBGame.java
  src/main/java/com/brandis/brandisweb/model/bgame/BGame.java
  src/main/java/com/brandis/brandisweb/model/bgame/BSavedGame.java
  src/main/java/com/brandis/brandisweb/model/bproduct/BProduct.java
  src/main/java/com/brandis/brandisweb/model/bproductbatch/AbstractBProductBatch.java
  src/main/java/com/brandis/brandisweb/model/bproductbatch/BProductBatch.java
  src/main/java/com/brandis/brandisweb/model/bproductbatch/BSavedProductBatch.java
  src/main/java/com/brandis/brandisweb/model/buser/BUser.java
  src/main/java/com/brandis/brandisweb/repository/BGameRepository.java
  src/main/java/com/brandis/brandisweb/repository/BProductPatchRepository.java
  src/main/java/com/brandis/brandisweb/repository/BProductRepository.java
  src/main/java/com/brandis/brandisweb/repository/BSavedGameRepository.java
  src/main/java/com/brandis/brandisweb/repository/BSavedProductBatchRepository.java
  src/main/java/com/brandis/brandisweb/repository/BUserRepository.java
  src/main/java/com/brandis/brandisweb/service/BGameService.java
  src/main/java/com/brandis/brandisweb/service/BProductPatchService.java
  src/main/java/com/brandis/brandisweb/service/BSavedGameService.java
  src/main/java/com/brandis/brandisweb/service/BSavedProductBatchService.java
  src/main/java/com/brandis/brandisweb/service/BUserService.java
  src/main/java/com/brandis/brandisweb/service/IProductBaseService.java
Labels: New functionality

#22 Added BGame repository,service and model.
  src/main/java/com/brandis/brandisweb/model/bproducer/BProducer.java
  src/main/java/com/brandis/brandisweb/repository/BProducerRepository.java
  src/main/java/com/brandis/brandisweb/service/BProducerService.java
Labels: New functionality

#27 Implement user registration.
  src/main/java/com/brandis/brandisweb/config/MvcConfig.java
  src/main/java/com/brandis/brandisweb/config/SecurityConfig.java
  src/main/java/com/brandis/brandisweb/controller/IndexController.java
  src/main/java/com/brandis/brandisweb/controller/UserController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: New functionality

#29 Added register functionality.
  pom.xml
  src/main/java/com/brandis/brandisweb/config/SecurityConfig.java
  src/main/java/com/brandis/brandisweb/controller/UserController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: Update

#30 Added more password validation
  src/main/java/com/brandis/brandisweb/config/DatabaseInitzr.java
  src/main/java/com/brandis/brandisweb/controller/UserController.java
  src/main/java/com/brandis/brandisweb/model/buser/BUser.java
  src/main/java/com/brandis/brandisweb/util/PasswordUtil.java
  src/main/resources/templates/login.html
Labels: New functionality

#32 Added react
  package-lock.json
  pom.xml
  src/main/frontend/.gitignore
  src/main/frontend/README.md
  src/main/frontend/package-lock.json
  src/main/frontend/package.json
  src/main/frontend/public/favicon.ico
  src/main/frontend/public/index.html
  src/main/frontend/public/login.html
  src/main/frontend/public/logo192.png
  src/main/frontend/public/logo512.png
  src/main/frontend/public/manifest.json
  src/main/frontend/public/robots.txt
  src/main/frontend/src/App.css
  src/main/frontend/src/App.js
  src/main/frontend/src/App.test.js
  src/main/frontend/src/index.css
  src/main/frontend/src/index.js
  src/main/frontend/src/logo.svg
  src/main/frontend/src/reportWebVitals.js
  src/main/frontend/src/setupTests.js
  src/main/frontend/yarn.lock
  src/main/resources/application.properties
  src/main/resources/templates/static/index.html
  src/main/resources/templates/static/login.html
Labels: New functionality

#37 implemented bgame fetching via axios to index page
  src/main/frontend/src/CompanyInfo.js
  src/main/java/com/brandis/brandisweb/controller/BGameController.java
  src/main/java/com/brandis/brandisweb/model/bgame/AbstractBGame.java
Labels: New functionality

#41 made navbar responsive
  src/main/frontend/public/index.html
  src/main/frontend/src/CompanyInfo.css
  src/main/frontend/src/CompanyInfo.js
  src/main/frontend/src/Menu.css
  src/main/frontend/src/Menu.js
  src/main/frontend/src/NavLogin.js
  src/main/frontend/src/Navbar.css
  src/main/frontend/src/Navbar.js
  src/main/java/com/brandis/brandisweb/controller/IndexController.java
Labels: enhancement

#43 Implemented basic game creation
  src/main/frontend/src/CompanyInfo.js
  src/main/frontend/src/LoginModal.js
  src/main/frontend/src/Menu.js
  src/main/frontend/src/NavLogin.js
  src/main/frontend/src/Navbar.js
  src/main/frontend/src/NewGameForm.js
  src/main/java/com/brandis/brandisweb/config/DatabaseInitzr.java
  src/main/java/com/brandis/brandisweb/config/SecurityConfig.java
  src/main/java/com/brandis/brandisweb/controller/BGameController.java
  src/main/java/com/brandis/brandisweb/controller/IndexController.java
  src/main/java/com/brandis/brandisweb/controller/UserController.java
  src/main/java/com/brandis/brandisweb/model/buser/BUser.java
  src/main/java/com/brandis/brandisweb/service/AuthorityService.java
  src/main/java/com/brandis/brandisweb/service/BGameService.java
Labels: New functionality

#47 ui improvements
  pom.xml
  src/main/frontend/public/index.html
  src/main/frontend/src/CompanyInfo.css
  src/main/frontend/src/LoginModal.js
  src/main/frontend/src/Menu.js
  src/main/frontend/src/NavLogin.css
  src/main/frontend/src/NavLogin.js
  src/main/frontend/src/Navbar.css
  src/main/frontend/src/Navbar.js
  src/main/frontend/src/RegisterModal.js
  src/main/java/com/brandis/brandisweb/config/SecurityConfig.java
  src/main/java/com/brandis/brandisweb/controller/IndexController.java
  src/main/java/com/brandis/brandisweb/controller/UserController.java
  src/main/java/com/brandis/brandisweb/service/BGameService.java
Labels: New functionality

#50 ui improvements
  pom.xml
  src/main/frontend/public/index.html
  src/main/frontend/src/App.js
  src/main/frontend/src/FinancesInfo.css
  src/main/frontend/src/FinancesInfo.js
  src/main/java/com/brandis/brandisweb/controller/UserController.java
Labels: New functionality

#51 48 creating side canvas for user actions
  src/main/frontend/src/Menu.js
  src/main/frontend/src/NavLogin.js
Labels: New functionality

#53 52 add backend functionality to finances component
  .gitignore
  pom.xml
  src/main/frontend/src/App.js
  src/main/frontend/src/CompanyInfo.js
  src/main/frontend/src/FinancesInfo.css
  src/main/frontend/src/FinancesInfo.js
  src/main/frontend/src/LoanModal.js
  src/main/frontend/src/TransferModal.js
  src/main/java/com/brandis/brandisweb/config/DatabaseInitzr.java
  src/main/java/com/brandis/brandisweb/config/SecurityConfig.java
  src/main/java/com/brandis/brandisweb/controller/BGameController.java
  src/main/java/com/brandis/brandisweb/controller/BSavedGameController.java
  src/main/java/com/brandis/brandisweb/controller/BusinessController.java
  src/main/java/com/brandis/brandisweb/controller/IndexController.java
  src/main/java/com/brandis/brandisweb/controller/UserController.java
  src/main/java/com/brandis/brandisweb/dto/GameDTO.java
  src/main/java/com/brandis/brandisweb/model/bgame/AbstractBGame.java
  src/main/java/com/brandis/brandisweb/model/bgame/BGame.java
  src/main/java/com/brandis/brandisweb/model/bgame/BSavedGame.java
  src/main/java/com/brandis/brandisweb/service/BGameService.java
  src/main/java/com/brandis/brandisweb/service/BSavedGameService.java
  src/main/java/com/brandis/brandisweb/service/IndexService.java
Labels: New functionality

#56 Main page functionality
  src/main/frontend/public/index.html
  src/main/frontend/src/App.js
  src/main/frontend/src/CompanyInfo.css
  src/main/frontend/src/CompanyInfo.js
  src/main/frontend/src/FinancesInfo.css
  src/main/frontend/src/FinancesInfo.js
  src/main/frontend/src/Game.js
  src/main/frontend/src/LoanModal.js
  src/main/frontend/src/Main.js
  src/main/frontend/src/Menu.js
  src/main/frontend/src/MerchantComponent.js
  src/main/frontend/src/Navbar.js
  src/main/frontend/src/Stats.js
  src/main/frontend/src/Table.css
  src/main/frontend/src/TransferModal.js
Labels: New functionality
